// Pure price → valuation logic. Given a per-holding price (already resolved into
// the holding's own currency by the caller), produce a `valuation` event worth
// `units held × price`. Holdings without tracked units can't be auto-priced and
// are reported as skipped (the UI surfaces why). No fetching/side effects here.

import type { Holding, HoldingEvent } from "../model/types";
import { netUnits } from "./holdings";

/** Marks a valuation as auto-generated by the price refresh. If a user edits
 *  today's auto-valuation, the marker is dropped (EventForm doesn't keep it), so
 *  a later refresh recognises the edit and won't clobber it. */
export const AUTO_VALUATION_NOTE = "auto: live price";

export interface PricedValuations {
  valuations: HoldingEvent[];
  skipped: Array<{ holding: Holding; reason: string }>;
}

export function buildValuations(
  holdings: Holding[],
  eventsByHolding: Map<string, HoldingEvent[]>,
  priceByHolding: Map<string, number>,
  date: string,
): PricedValuations {
  const valuations: HoldingEvent[] = [];
  const skipped: Array<{ holding: Holding; reason: string }> = [];

  for (const h of holdings) {
    const price = priceByHolding.get(h.id);
    if (price === undefined) continue; // no ticker / no quote this run → leave as-is
    // Reject <= 0 too: a price of exactly 0 isn't meaningful for a held position
    // and would silently zero the holding's value (and net worth).
    if (!Number.isFinite(price) || price <= 0) {
      skipped.push({ holding: h, reason: "bad price" });
      continue;
    }
    const events = eventsByHolding.get(h.id) ?? [];
    const units = netUnits(events);
    if (units === null) {
      skipped.push({ holding: h, reason: "units not tracked — record buys with units × price" });
      continue;
    }
    if (units <= 0) {
      skipped.push({ holding: h, reason: "no units held" });
      continue;
    }
    // Deterministic per-(holding, day) id: re-refreshing the same day OVERWRITES
    // today's auto-valuation (one clean daily mark; manual valuations use random
    // ids, so no collision). BUT if the user manually edited today's auto mark,
    // EventForm dropped the AUTO_VALUATION_NOTE marker — so DON'T overwrite their
    // correction.
    const autoId = `auto-${h.id}-${date}`;
    const existing = events.find((e) => e.id === autoId);
    if (existing && existing.note !== AUTO_VALUATION_NOTE) {
      skipped.push({ holding: h, reason: "today's value was edited manually — not overwritten" });
      continue;
    }
    valuations.push({
      id: autoId,
      holdingId: h.id,
      date,
      type: "valuation",
      amount: units * price,
      // Carry the per-unit price so the store can RE-derive amount = current units
      // × price at commit time (inside its serialization lock). The `units` above
      // were read when the fetch STARTED; if a concurrent edit or another refresh
      // changed the position during the network await, recomputing from live units
      // at write time prevents a stale-units value from being persisted.
      price,
      note: AUTO_VALUATION_NOTE,
      createdAt: new Date().toISOString(),
    });
  }
  return { valuations, skipped };
}
